// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8e1dZpzwGVok9EHXuNSvec5ADAU_kdb0',
    appId: '1:682530565593:web:49a321e4bb4b1a920ffdc8',
    messagingSenderId: '682530565593',
    projectId: 'mahaweliauthoritygroupproject',
    authDomain: 'mahaweliauthoritygroupproject.firebaseapp.com',
    storageBucket: 'mahaweliauthoritygroupproject.firebasestorage.app',
    measurementId: 'G-JWC3XG4CC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhf8eWf9S4NVrExsD1mp4WbCowPMlaisk',
    appId: '1:682530565593:android:9fbf9607954543c90ffdc8',
    messagingSenderId: '682530565593',
    projectId: 'mahaweliauthoritygroupproject',
    storageBucket: 'mahaweliauthoritygroupproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVYZd-DZ85JyK2ygEwJBvURJhfuC0g-c4',
    appId: '1:682530565593:ios:0209536f02891dc00ffdc8',
    messagingSenderId: '682530565593',
    projectId: 'mahaweliauthoritygroupproject',
    storageBucket: 'mahaweliauthoritygroupproject.firebasestorage.app',
    iosBundleId: 'com.example.mahaweliAdminSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVYZd-DZ85JyK2ygEwJBvURJhfuC0g-c4',
    appId: '1:682530565593:ios:0209536f02891dc00ffdc8',
    messagingSenderId: '682530565593',
    projectId: 'mahaweliauthoritygroupproject',
    storageBucket: 'mahaweliauthoritygroupproject.firebasestorage.app',
    iosBundleId: 'com.example.mahaweliAdminSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8e1dZpzwGVok9EHXuNSvec5ADAU_kdb0',
    appId: '1:682530565593:web:e24a862ab1ff9bec0ffdc8',
    messagingSenderId: '682530565593',
    projectId: 'mahaweliauthoritygroupproject',
    authDomain: 'mahaweliauthoritygroupproject.firebaseapp.com',
    storageBucket: 'mahaweliauthoritygroupproject.firebasestorage.app',
    measurementId: 'G-X9T4FHLK0T',
  );
}
